### ISSUE TITLE
Bug on Vista x64/VS2010

### ISSUE THREAD

**Issue by vdcprivate** [endjin/Templify#14]
I am experiencing a bug under Vista x64 with SP2 & VS2010

The Templify executable will finish without any confirm message ("Package Sucessfully Deployed"). 
Moreover the folders names, as well as the Visual Studio project and solution file names, all have a name starting with "**NAME**" and not with the name I gave to it ("SharpfirstSample"). Please note that there are 2 underscore chars around the "NAME" that actually the github editor use to convert to bold text...

As I cant attach images here to show you what I mean please click on the following link to get an image sample from my google docs repository.
https://docs.google.com/leaf?id=0B9IY0bJiYPdrYzcwNjM5NDUtNGUxNy00NzljLTlhYTYtMWVhYTI5YWRhYTYx&hl=it

Opening the project and solution file with Notepad will give you a general idea of the content

Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "**NAME**.Core", "app__NAME__.Core__NAME__.Core.csproj", "{7696B4F6-2A10-40C4-A1E2-B9768182588C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "**NAME**.ApplicationServices", "app__NAME__.ApplicationServices__NAME__.ApplicationServices.csproj", "{EA00777D-3D7A-4406-8BFB-E5A90CF0E8A9}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "**NAME**.Data", "app__NAME__.Data__NAME__.Data.csproj", "{63E9AECE-3385-44F0-BDF9-4C01DD3C0647}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "**NAME**.Web.Controllers", "app__NAME__.Web.Controllers__NAME__.Web.Controllers.csproj", "{518B2E4B-2B9B-48EF-8736-DDB6A0F78E79}"
EndProject

**Comment by rupertbates** [comment]
I'm also experiencing this issue under Win 7 64bit with VS 2010 and version 0.5.0.0 of Templify

**Comment by morcs** [comment]
I'm afraid I still have the issue in version 0.6.14983.000.

I now get a "System.OutOfMemoryException" though, which may help track it down.

Interestingly this only happens when I try to create a template under C:\Projects. It works OK if I create one under C:\Projects\SharpArchitecture.

(OS is Windows 7, 64-bit)

**Comment by HowardvanRooijen** [comment]
Hi,

can you see if there are any error logs under:

AppData\Roaming\Endjin\Templify\errors

and if so post the stack trace?

Thanks!

**Comment by morcs** [comment]
No probs:

```
Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Endjin.Templify.Domain.Domain.Packager.Processors.FileContentProcessor.ReadContents(String path) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Domain\Packager\Processors\FileContentProcessor.cs:line 18
   at Endjin.Templify.Domain.Domain.Packager.Tokeniser.TemplateTokeniser.TokeniseFileContent(String file, Dictionary`2 tokens) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Domain\Packager\Tokeniser\TemplateTokeniser.cs:line 36
   at Endjin.Templify.Domain.Domain.Packager.Processors.PackageProcessor.ProcessFileContents(IEnumerable`1 files, Dictionary`2 tokens) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Domain\Packager\Processors\PackageProcessor.cs:line 102
   at Endjin.Templify.Domain.Domain.Packager.Processors.PackageProcessor.ProcessFiles(String path, Dictionary`2 tokens) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Domain\Packager\Processors\PackageProcessor.cs:line 76
   at Endjin.Templify.Domain.Domain.Packager.Processors.PackageProcessor.Process(String path, Dictionary`2 tokens) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Domain\Packager\Processors\PackageProcessor.cs:line 47
   at Endjin.Templify.Domain.Tasks.PackageDeployerTasks.RunDeployPackage() in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Tasks\PackageDeployerTasks.cs:line 94
   at Endjin.Templify.Domain.Tasks.PackageDeployerTasks.DeployPackage(CommandOptions options) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Tasks\PackageDeployerTasks.cs:line 66
   at Endjin.Templify.Client.ViewModel.DeployPackageViewModel.ExecutePackage() in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Client\ViewModel\DeployPackageViewModel.cs:line 91
   at Endjin.Templify.Domain.Framework.Threading.BackgroundWorkerManager.<>c__DisplayClass3.<RunBackgroundWork>b__0(Object , DoWorkEventArgs ) in C:\_Projects\endjin\OSS\Templify\Solutions\Endjin.Templify.Domain\Framework\Threading\BackgroundWorkerManager.cs:line 15
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
