### ISSUE TITLE
Error occurred when templifiing a visualstudio folder structure 

### ISSUE THREAD

**Issue by IvanMilano** [endjin/Templify#34]
Here is the stack trace from the error file:

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Endjin.Templify.Domain.Domain.Packager.Builders.ClonePackageBuilder.Build(Package package) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Domain\Packager\Builders\ClonePackageBuilder.cs:line 41
   at Endjin.Templify.Domain.Tasks.PackageCreatorTasks.RunCreatePackage() in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Tasks\PackageCreatorTasks.cs:line 89
   at Endjin.Templify.Domain.Tasks.PackageCreatorTasks.CreatePackage(CommandOptions options) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Tasks\PackageCreatorTasks.cs:line 74
   at Endjin.Templify.Client.ViewModel.CreatePackageViewModel.ExecuteCreatePackage() in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Client\ViewModel\CreatePackageViewModel.cs:line 74
   at Endjin.Templify.Domain.Framework.Threading.BackgroundWorkerManager.<>c__DisplayClass3.<RunBackgroundWork>b__0(Object param0, DoWorkEventArgs param1) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Framework\Threading\BackgroundWorkerManager.cs:line 15
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by yosoyadri** [comment]
Same here. Templifying a VS2012 solution folder

**Comment by ghost** [comment]
Same here. VS2013 solution. Works fine on another VS2013 solution so it's not a Templify install issue.

For me this was an issue with the solution having been created from another template which resulted in a Manifest.xml file existing at the root of the solution. Deleting the file solved the problem.
