### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SimonTorm** [endjin/Templify#35]
When I templify a folder, using v0.7.0.25, I do get a popup with the statement that there are errors.

This is the error output:

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Endjin.Templify.Domain.Domain.Packager.Builders.ClonePackageBuilder.Build(Package package) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Domain\Packager\Builders\ClonePackageBuilder.cs:line 41
   at Endjin.Templify.Domain.Tasks.PackageCreatorTasks.RunCreatePackage() in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Tasks\PackageCreatorTasks.cs:line 89
   at Endjin.Templify.Domain.Tasks.PackageCreatorTasks.CreatePackage(CommandOptions options) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Tasks\PackageCreatorTasks.cs:line 74
   at Endjin.Templify.Client.ViewModel.CreatePackageViewModel.ExecuteCreatePackage() in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Client\ViewModel\CreatePackageViewModel.cs:line 74
   at Endjin.Templify.Domain.Framework.Threading.BackgroundWorkerManager.<>c__DisplayClass3.<RunBackgroundWork>b__0(Object param0, DoWorkEventArgs param1) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Framework\Threading\BackgroundWorkerManager.cs:line 15
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Any idea what's wrong ?

Thanks,
Simon

**Comment by HowardvanRooijen** [comment]
That's not a very helpful error message (my bad). Something went wrong trying to clone the package. Are you templifying a folder and one / some of the files are locked by another process?

**Comment by SimonTorm** [comment]
I already looked with procesexp and nothing is in use in the directory structure. I am going to reboot now and let you know.

**Comment by HowardvanRooijen** [comment]
Can you templify _any_ arbitrary folder? If not the only two ways forward are to either send me the source so I can debug it, or for you to download the source and step through it.

**Comment by SimonTorm** [comment]
It is still raising an error after the reboot. I can't send you the source, it is a business project. I can debug it if you want.

I tried to templify another solution and it is also failing, so it looks like my system is causing this.

**Comment by HowardvanRooijen** [comment]
Can you templify a folder that may not have a solution in it?

**Comment by SimonTorm** [comment]
yes, that's working

**Comment by HowardvanRooijen** [comment]
BTW there is info in this thread about how to set up debugging: https://github.com/endjin/Templify/issues/23

**Comment by SimonTorm** [comment]
Ok, found it. I can templify en deploy it. 

The solution: I was trying to templify a folder which was already deployed from your util some time ago. Your util is putting a manifest.xml in the root dir of the deployed folder. Removing the manifest.xml file from the solution and the templify it was the solution.

Thanks for all the help, especially on a Saturday.

**Comment by HowardvanRooijen** [comment]
NP - I've opened a new issue to stop that from happening in the future: https://github.com/endjin/Templify/issues/36

**Comment by SimonTorm** [comment]
Ok!

Thanks again for the nice work.

Have a great weekend.

**Comment by smartcodingxx** [comment]
Hi,
Error occured while templifying vs2012 solution which is having installshield project. I tried the above solution by removing manifest.xml file from solution but still I am getting error. Here the error log.

Is it still something there which I forget to remove like manifest file.
Thanks,
Dharmendra

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Endjin.Templify.Domain.Domain.Packager.Tokeniser.PackageTokeniser.TokeniseFileContent(Package package, Dictionary`2 tokens) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Domain\Packager\Tokeniser\PackageTokeniser.cs:line 70
   at Endjin.Templify.Domain.Domain.Packager.Tokeniser.PackageTokeniser.Tokenise(Package package, Dictionary`2 tokens) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Domain\Packager\Tokeniser\PackageTokeniser.cs:line 46
   at Endjin.Templify.Domain.Tasks.PackageCreatorTasks.RunCreatePackage() in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Tasks\PackageCreatorTasks.cs:line 90
   at Endjin.Templify.Domain.Tasks.PackageCreatorTasks.CreatePackage(CommandOptions options) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Tasks\PackageCreatorTasks.cs:line 74
   at Endjin.Templify.Client.ViewModel.CreatePackageViewModel.ExecuteCreatePackage() in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Client\ViewModel\CreatePackageViewModel.cs:line 74
   at Endjin.Templify.Domain.Framework.Threading.BackgroundWorkerManager.<>c__DisplayClass3.<RunBackgroundWork>b__0(Object param0, DoWorkEventArgs param1) in c:\TeamCity\Server\buildAgent\work\595123988a1f1535\Solutions\Endjin.Templify.Domain\Framework\Threading\BackgroundWorkerManager.cs:line 15
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by HowardvanRooijen** [comment]
Hmm - I wonder if you have a file that can't be written to / processed? Have a look at the files in that directory and see if there's anything suspicious - then you can add it as an exclusion. If you don't find anything - put another comment on here and we'll take a look.
